imports:
  - plugin:cloudify-utilities-plugin?version= >=1.22.1

inputs:
  website_message:
    type: string
    description: Text to be displayed on the webpage.
    default: Hello world!

node_templates:

  install_nginx:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create: 
          implementation: scripts/install_nginx.sh
    relationships:
      - type: cloudify.relationships.contained_in
        target: vm

  install_app:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create: 
          implementation: scripts/install_app.sh
          inputs:
              message: { get_input: website_message }
    relationships:
      - type: cloudify.relationships.contained_in
        target: vm
      - type: cloudify.relationships.depends_on
        target: install_nginx
